backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "global"
    label: "Global Settings"
    files:
      - label: "Header"
        name: "header"
        file: "header.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
